### ISSUE TITLE
username and password authentication

### ISSUE THREAD

**Issue by ecsuae** [soulteary/docker-nginx-forward-proxy#1]
First of all I would like to thank you for such a easy way to configure the proxy.I am just wondering is it possible to add username and password authentication for the proxy users??

**Comment by soulteary** [comment]
Hi, I use it in combination with Traefik, whether it is [forwardauth](https://doc.traefik.io/traefik/middlewares/forwardauth/) or [basicauth](https://doc.traefik.io/traefik/middlewares/basicauth/), it's good to use.

If you just want to use nginx, you can try it: https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/
